### ISSUE TITLE
How to get history for named account?

### ISSUE THREAD

**Issue by mnastalek** [jwilk/mbank-cli#64]
Hello, i have two accounts: 
$ perl mbank-cli
eKonto - podstawowe     71 1140 2004 0000 3102 7506 7112           1489.99 PLN     1423.76 PLN
eKonto - FIRMA  41 1140 2004 0000 3402 7508 9185             326851.51 PLN       326851.51 PLN

How can i get history for one of this? 
$ perl mbank-cli history eKonto -  #FIRMA
mbank-cli: history: no matching accounts

Trying all diffrent combination with same result.

**Comment by jwilk** [comment]
You need to pass the whole account name as a single argument, e.g. by putting single quotes around the name:
```console
$ perl mbank-cli history 'eKonto - FIRMA'
```
The `-A` option can be used to print history of all accounts:
```console
$ perl mbank-cli history -A
```

**Comment by mnastalek** [comment]
Ohh i see ;) Thanks.
