### ISSUE TITLE
Scraping error: history.menu

### ISSUE THREAD

**Issue by TheKerimek** [jwilk/mbank-cli#65]
Suddenly today:

Scraping error: history.menu:  at ./mbank-cli line 1107
	main::_prepare_history('HASH(0x22d79a0)') called at ./mbank-cli line 1151
	main::do_history('selection', 'ARRAY(0x1a48268)', 'display_name', 0, 'login', 'HASH(0x22d79a0)', 'accounts', 'ARRAY(0x252e6b0)', 'start_date', ...) called at ./mbank-cli line 2509

**Comment by jwilk** [comment]
Happens to me too. I'm looking into it.

**Comment by jwilk** [comment]
I've made a quick&dirty fix in 8e30129f525f6c9b648c99f298816bb5cb880c35.
I'll try to clean it up and make a new release later today.

**Comment by chilek** [comment]
> I've made a quick&dirty fix in 8e30129.

I confirm it solves the problem.

**Comment by TheKerimek** [comment]
thanks mate, I can also confirm that now it works fine!

**Comment by jwilk** [comment]
Fixed in 1.6.4.
