### ISSUE TITLE
adding script as trusted device stopped working

### ISSUE THREAD

**Issue by chilek** [jwilk/mbank-cli#89]
As in subject.
Till yesterday mbank-cli was able to add himself as trusted devices on bank servers and thus it allowed to launch script cyclic from cron without mobile app ack requirement.
Has mbank changed unique device id calculation? My guess goes from the fact the my browser had to be re-marked as trusted too.

**Comment by jwilk** [comment]
Everything works fine here. I can still log in without SMS password.

**Comment by chilek** [comment]
```bash
m -f ~/.local/share/mbank-cli/*.cookies
```

probably resolved my problem. Let's wait a day to confirm it.

**Comment by chilek** [comment]
Unfortunately still the same problem.
Removed all trusted devices from mbank www panel, and newly added pc web browser and launched
mbank-cli script. Although mobile app authorization works, script instance is not added to trusted devices :(

**Comment by jwilk** [comment]
Just a sanity check: did you run `mbank-cli register-device` after removing the cookies?

**Comment by chilek** [comment]
Completely forgottent about required register-device! Thanks for hint. Of course it helped!
