### ISSUE TITLE
login.redirect-url /dashboard does not match /(*FAIL)/

### ISSUE THREAD

**Issue by piotrcichosz** [jwilk/mbank-cli#92]
~/projects/mbank-cli$ mbank
Scraping error: login.redirect-url: "/dashboard" does not match /(*FAIL)/ at /home/piotr/projects/mbank-cli/mbank-cli line 277.
	main::match("/dashboard", qr((*FAIL)), "context", "login.redirect-url") called at /home/piotr/projects/mbank-cli/mbank-cli line 285
	main::no_match("/dashboard", "context", "login.redirect-url") called at /home/piotr/projects/mbank-cli/mbank-cli line 1936
	main::do_login() called at /home/piotr/projects/mbank-cli/mbank-cli line 4012
	main::main() called at /home/piotr/projects/mbank-cli/mbank-cli line 4043

I have registered device and last time before that error I used mbank-cli 1 day ago. I'm using pu/84 branch, if that matter somehow.
First 2 attempts gave me this error, 3rd one - successfully listed accounts.

**Comment by jwilk** [comment]
Duplicate of #88.

>I'm using pu/84 branch, if that matter somehow.

That branch was stale.
I've rebased it on top master, so it should work now.
